### ISSUE TITLE
Changes to pokedex content model

### ISSUE THREAD

**Issue by balsama** [drupal-speedrun/speedrun#2]
Now that we have actual data for the pokemon content, what changes need to be made? @phenaproxima ? I know you said something about the long plaintext field. And I opened #1 for the alt text. What else?

**Comment by phenaproxima** [comment]
Abilities should be a multi-value plain text field (not long text), but other than that I don't think we have a problem.

**Comment by balsama** [comment]
@phenaproxima Can you merge i2 into 8.0.x?
