### ISSUE TITLE
Imported Pokemon entities reference non-existent Type vocab terms

### ISSUE THREAD

**Issue by balsama** [drupal-speedrun/speedrun#4]
This is probably to be expected. I would guess that the terms need to be created before a refernce field could be populated :)

@phenaproxima another import/migrations _prior_ to the pokedex?

**Comment by phenaproxima** [comment]
That's actually what's already happening -- it imports terms before importing Pokémon, for exactly that reason. It's not possible to reference a non-existent term; I'd imagine that'd throw some sort of data integrity exception on save.

**Comment by balsama** [comment]
Indeed there is an error when saving (outside of the import):

```
This entity (taxonomy_term: nn) cannot be referenced.
```

And I don't see any terms in the type vocab.
